In [1]:
import os
import os.path as osp
import torch

In [2]:
name='cora'
hl_path = osp.join('..\\data\\' + name + '\\HL_' + name + '.pt')
HL = torch.load(hl_path)
print(HL)

{1: SparseTensor(row=tensor([   0,    0,    0,  ..., 2707, 2707, 2707]),
             col=tensor([   0,  633, 1862,  ..., 1473, 2706, 2707]),
             val=tensor([0.5000, 0.1667, 0.1443,  ..., 0.1250, 0.1250, 0.5000]),
             size=(2708, 2708), nnz=13264, density=0.18%), 2: SparseTensor(row=tensor([   0,    0,    0,  ..., 2707, 2707, 2707]),
             col=tensor([   0, 1862, 2582,  ..., 1473, 2706, 2707]),
             val=tensor([0.3333, 0.3333, 0.3333,  ..., 0.2000, 0.1721, 0.3333]),
             size=(2708, 2708), nnz=7158, density=0.10%), 3: SparseTensor(row=tensor([   4,    4,    4,  ..., 2707, 2707, 2707]),
             col=tensor([   4, 1016, 1256,  ..., 1473, 2706, 2707]),
             val=tensor([0.2500, 0.1021, 0.1768,  ..., 0.2500, 0.1768, 0.2500]),
             size=(2708, 2708), nnz=2029, density=0.03%)}


In [7]:
hl_path = osp.join('..\\data\\' + name + '\\HL_' + name + '_3.pt')
HL2 = torch.load(hl_path)
print(HL2)

{1: SparseTensor(row=tensor([   0,    0,    0,  ..., 2707, 2707, 2707]),
             col=tensor([   0,  633, 1862,  ..., 1473, 2706, 2707]),
             val=tensor([0.5000, 0.1667, 0.1443,  ..., 0.1250, 0.1250, 0.5000]),
             size=(2708, 2708), nnz=13264, density=0.18%), 2: SparseTensor(row=tensor([   0,    0,    0,  ..., 2707, 2707, 2707]),
             col=tensor([   0, 1862, 2582,  ..., 1473, 2706, 2707]),
             val=tensor([0.3333, 0.3333, 0.3333,  ..., 0.2000, 0.1721, 0.3333]),
             size=(2708, 2708), nnz=7158, density=0.10%)}


In [9]:
a = torch.tensor([[1,2,3],[7,0.0,1.2]])
print(a)

tensor([[1.0000, 2.0000, 3.0000],
        [7.0000, 0.0000, 1.2000]])


In [11]:
b = torch.ones(a.size())
print(b)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [20]:
z=[]
z.append(a)
z.append(b)
c=torch.stack(z, dim=0)
print(c)
print(c.size())
t = torch.ones(3,1)
print(t)

tensor([[[1.0000, 2.0000, 3.0000],
         [7.0000, 0.0000, 1.2000]],

        [[1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000]]])
torch.Size([2, 2, 3])
tensor([[1.],
        [1.],
        [1.]])


In [22]:
s=torch.einsum('bij,jk->ik', c,t )
print(s)

tensor([[ 9.0000],
        [11.2000]])


In [26]:
torch.mm(a,t)

tensor([[6.0000],
        [8.2000]])

In [33]:
print(a)
t=[a,a]

print(t)

tensor([[1.0000, 2.0000, 3.0000],
        [7.0000, 0.0000, 1.2000]])
[tensor([[1.0000, 2.0000, 3.0000],
        [7.0000, 0.0000, 1.2000]]), tensor([[1.0000, 2.0000, 3.0000],
        [7.0000, 0.0000, 1.2000]])]


In [37]:
for i in range(2,10,2):
    print(i)

2
4
6
8


In [41]:
a = torch.Tensor(1)
print(a)

tensor([0.])
